name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: wendyliga
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wendyliga
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: startsWith(github.ref, 'refs/tags') != true && github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2

      - name: Deploy edge
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            wendyliga/wrangler:edge
            ghcr.io/wendyliga/wrangler:edge

      - name: Docker meta
        id: meta
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/metadata-action@v3
        with:
          images: wendyliga/wrangler,ghcr.io/wendyliga/wrangler
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: Deploy release
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
